[package]
name = "matchar_app_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
matchar_app_adapter = { path = "../matchar_app_adapter" }
matchar_app_service = { path = "../matchar_app_service" }
