[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
matchit = "0.8.4"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
