[workspace]
resolver = "2"
members = [
  "backend/matchar_app_adapter",
  "backend/matchar_app_backend",
  "backend/matchar_app_service",
]

[workspace.dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["tokio", "json", "query"] }
thiserror = "2.0.10"
tokio = { version = "1.43.0", features = ["full"] }
