[package]
name = "matchar_app_service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
refinement = { path = "../refinement" }
thiserror = { workspace = true }
time = { workspace = true }
