[package]
name = "postbox"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7.13"
uuid = { workspace = true }
