[package]
name = "oauth2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
oauth2 = "4.4.2"
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
